BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBBBB

BBBBB BBBBB
    XXXXXXXXX XXXXX XXXXXXX  XX
    X
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX

            XX XXXX XXXXX XXX XXX XXX XXX XXXXXXXXX XXX XXXXX XXXXXXXXXXXX XX XXX XXXX XXXXXX
            XXX XXX XXXXXXXX XX XX XXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXX XX
            XXXXXXXX XXX
            XXXXXX XX XXXXX
            XXXXXXXXXXXXX XX XXXXXXXXXXXX X XXXXX XXXX XXXX XXXXXXXXX XXX XXXXXXXX XXX XXXXXX XX XXXXXXX
            XXXXXXXXXXX XX  XXXXXXX

        XXXXXX
    XXXXXX



    BB BBBBBBBBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                
            XXXXXX
        BBBBBB
    BBBBB

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        
        XXXXXXX
        XXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XX XXXXX XXXXXXXXXXXX
        XXXXX
        XXXXXXXX

        BBB BBBB BB BBBBBBBBBBBBB
            XXXX
                XXXXXXXXXX XXXXX
                XXXXXXXXX
                XXXXBBBBBBBBB BBBBBBBBBBB BBBBBBBBXXXXX
                BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                    
                BBBBBB
                XXX XXXXXXXXXXX
            XXXXX

        BBBBBB
    XXXXXXXX

    BBBBBBBBBBB


BBBBBBBB
BBBBB BBBBBB
    XXXXXXX
        XXXXXX X
            XXXXXXXX XXXXX XXXXXXXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXXX
        XXXXXXXXXX XX X
            XXX XXXXXXXXXX X FFFFX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
                XXX XXXXXXXX X XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXX
                XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        XXX
    XXXXXXXXX
BBBBBBBB